<a href="https://colab.research.google.com/github/StephenManoharGurram/ICP-3/blob/main/ICP3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Using NumPy create random vector of size 15 having only Integers in the range 1-20.
1. Reshape the array to 3 by 5
2. Print array shape.
3. Replace the max in each row by 0

Create a 2-dimensional array of size 4 * 3 (composed of 4-byte integer elements), also print the shape. of the array.

In [3]:
import numpy as np

# Step 1: Create a random vector of size 15 with integers in the range 1-20
random_vector = np.random.randint(1, 21, size=15)
print(random_vector)
# Step 2: Reshape the array to 3 by 5
reshaped_array = random_vector.reshape(3, 5)
# Step 3: Print array shape
print("Shape of the reshaped array:", reshaped_array.shape)
# Step 4: Replace the max in each row by 0
for row in reshaped_array:
    row[np.argmax(row)] = 0

print("Array after replacing the max in each row by 0:")
print(reshaped_array)

# Create a 2-dimensional array of size 4 * 3 with 4-byte integer elements
array_4x3 = np.zeros((4, 3), dtype=np.int32)

# Print the shape of the 2-dimensional array
print("Shape of the 2-dimensional array:", array_4x3.shape)
print(array_4x3)


[ 6  1  1  1 14  2 17  7 12  1  3 19 16  1 10]
Shape of the reshaped array: (3, 5)
Array after replacing the max in each row by 0:
[[ 6  1  1  1  0]
 [ 2  0  7 12  1]
 [ 3  0 16  1 10]]
Shape of the 2-dimensional array: (4, 3)
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


Write a program to compute the eigenvalues and right eigenvectors of a given square array given below: [[3-2] [10]]

In [4]:
import numpy as np

# Define the square array
matrix = np.array([[3, -2],
                   [0, 10]])

# Compute the eigenvalues and right eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

# Print the eigenvalues and right eigenvectors
print("Eigenvalues:")
print(eigenvalues)

print("\nRight Eigenvectors:")
print(eigenvectors)


Eigenvalues:
[ 3. 10.]

Right Eigenvectors:
[[ 1.         -0.27472113]
 [ 0.          0.96152395]]


Compute the sum of the diagonal element of a given array.

[[012]

[345]]



In [5]:
import numpy as np

# Define the array
matrix = np.array([[0, 1, 2],
                   [3, 4, 5]])

# Compute the sum of the diagonal elements
diagonal_sum = np.trace(matrix)

# Print the sum of the diagonal elements
print("Sum of the diagonal elements:", diagonal_sum)


Sum of the diagonal elements: 4


Write a NumPy program to create a new shape to an array without changing its data.

Reshape 3x2:

[[12]

[34]

[56]]

Reshape 2x3:

[[123]

[456]]

In [6]:
import numpy as np

# Define the original 3x2 array
original_array = np.array([[1, 2],
                           [3, 4],
                           [5, 6]])

# Reshape the array to 2x3
reshaped_array = original_array.reshape(2, 3)

# Print the original and reshaped arrays
print("Original array (3x2):")
print(original_array)

print("\nReshaped array (2x3):")
print(reshaped_array)


Original array (3x2):
[[1 2]
 [3 4]
 [5 6]]

Reshaped array (2x3):
[[1 2 3]
 [4 5 6]]
